# Generated by Django 2.0.2 on 2020-04-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('Exec_No', models.AutoField(help_text='Unique Exec no for Executive table', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Executive first name', max_length=14)),
                ('Last_Name', models.CharField(blank=True, help_text='Executive last name', max_length=14, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('Birth_Date', models.DateField(blank=True, help_text='Executive birth date', null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Mobile_Number', models.PositiveIntegerField(default=0)),
                ('Email_Address', models.EmailField(max_length=80, unique=True)),
                ('Hire_Date', models.DateField(help_text='Executive joining date')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Man_No', models.AutoField(help_text='Unique Man no for Manager table', primary_key=True, serialize=False)),
                ('First_Name', models.CharField(help_text='Manager first name', max_length=14)),
                ('Last_Name', models.CharField(blank=True, help_text='Manager last name', max_length=14, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('Birth_Date', models.DateField(blank=True, help_text='Manager birth date', null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('Mobile_Number', models.PositiveIntegerField(default=0)),
                ('Email_Address', models.EmailField(max_length=80, unique=True)),
                ('Hire_Date', models.DateField(help_text='Manager joining date')),
            ],
        ),
        migrations.AlterField(
            model_name='execleaverequest',
            name='Exec_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Exec_ID', to='emp.Executive'),
        ),
        migrations.AlterField(
            model_name='execleaverequest',
            name='Man_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Emp_No', to='emp.Manager'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Allocated_Days',
            field=models.PositiveIntegerField(default=0, help_text='No of leave days allocated to a leave type per executive per year'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Available_Days',
            field=models.PositiveIntegerField(default=0, help_text='Remaining/available leave days per executive'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='Exec_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.Executive'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
