# Generated by Django 2.0.2 on 2020-04-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200430_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='Man_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Man_ID', to='emp.Manager'),
        ),
    ]
