# Generated by Django 2.0.2 on 2020-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_executive_man_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('AP', 'Approved'), ('DL', 'Declined'), ('CA', 'Cancelled'), ('PE', 'Pending')], default='PE', max_length=10),
        ),
    ]
