# Generated by Django 2.2.10 on 2020-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_auto_20200430_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execleaverequest',
            name='Leave_Status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('DL', 'Declined'), ('CA', 'Cancelled')], default='PE', max_length=10),
        ),
    ]
